### ISSUE TITLE
[v0.0] Make schedule for writing first complete version

### ISSUE THREAD

**Issue by skkwan** [skkwan/thesis#1]
Introduction: first-half of February (Feb 1 - Feb 15, which is 12 business days) - leaving ROOT Hackathon Feb 13-14 blocked

Each day: spend one-hour
- [x] Feb 1, 2 - The Standard Model
- [x] Feb 5, 6 - Gauge groups
- [x] Feb 7, 8 - The Higgs mechanism
- [x] Feb 9, 12 - 2HDM+S
- [x] Feb 15 - TRSM 

CERN, the LHC, and the CMS Detector; Phase-2 L1 Trigger work (6 business days)

- [x] Feb 16 - CERN and the Large Hadron Collider
- [x] Feb 18 - (Not-writing) Lock down FPO timeline
- [x] Feb 18 - The CMS Detector
- [x] Feb 20 - Sub-detectors
- [x] Feb 21 - The Level-1 Trigger and High Level Trigger
- [x] Feb 22 - ParticleFlow and Computational Infrastructure
- [x] Feb 23 - Phase-2 Upgrade of CMS, including the L1 Trigger
- [x] Feb 24, 25 - Double with writing Detector Performance note: mostly figures The Phase-2 Upgrade of the Level-1 Trigger: EGamma standalone barrel reconstruction in Phase 2 

Feb 26 checkpoint for current chapters
- [x] Feb 25 - Edit introduction 
- [x] Feb 25 - Edit CERN + LHC + CMS section
- [x] Feb 26 - send current chapters to advisor

Run-2 h->aa->bbtautau analysis, h->a1a2
- [x] Feb 26 - Text edits from Issue #3 
- [x] Feb 27 - Formatting and spellcheck implementation
- [x] Feb 28 - Object selection: Muon, tau, b-tagging physics, decay modes, reconstruction, and ID
- [x] Feb 29 - Samples, event selection, scale factors and corrections
- [x] Mar 1 - Background estimation, put in citations
- [x] Mar 2 
    - [x] DNN and event categorization
    - [x] Systematic uncertainties
- [x] Mar 3 
   - [x] Dedicated discussion of SVFit and FastMTT
   - [x] Statistical fitting, include pulls and impacts
   - [x] Results

Mar 4 checkpoint for current chapters
- [x] Mar 4 morning
   - [x] Combination from bbmumu
   - [x] Abstract and title
   - [x] Send current chapters to advisor
- [x] Mar 4: Issue #5 : Chapter 7: expand on mutau, etau, and emu event selections
- [x] Mar 5: Issue #5 : Find representative plots on SVFit/FastMTT reconstruction
- [x] Mar 5, Mar 6, Mar 7 Issue #5 : Expand on Scale factors and corrections
- [x] Mar 8: (Morning) Issue #5: Fix text in Section 11.1.1 on uncertainties in the lepton energy scale, as this is now inaccurate
- [x] Mar 8: (Afternoon), Mar 9: Write chapter on statistical fitting 
- [x] Mar 9: Asymmetric sample gen studies

Mar 11 full draft checkpoint
Mar 11, Mar 12, Mar 13, Mar 14 - no major writing, got revisions on Mar 13 
- [x] Mar 15: Issue #6 : first batch of changes
- [x] Mar 16: Issue #6: second batch of changes
- [x] Mar 18: Issue #6: flesh out results and write conclusion and outlook
- [x] Mar 18: Send revisions to advisor

**Comment by skkwan** [comment]
Closing this issue as all chapters are present, opening new issue for `v0.1`.
